# Generated by Django 4.0 on 2021-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='myFiles')),
                ('nom', models.CharField(max_length=50)),
                ('typeFile', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
